# Generated by Django 3.0.8 on 2020-10-13 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Nutrition',
            new_name='Fitness',
        ),
    ]
